/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Josu Alvarez <jalvarez041.ehu.eus>
 */
public class MenuLogin extends javax.swing.JPanel implements ActionListener {

    private String dificultad_juego = "facil";

    /**
     * Creates new form VistaLogin
     */
    public MenuLogin() {
        initComponents();
        inicializarBotonesDificultad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        grupoBotonesDif = new javax.swing.ButtonGroup();
        labelUsuario = new javax.swing.JLabel();
        labelPasswd = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        labelPideSelDif = new javax.swing.JLabel();
        labelBienvenida = new javax.swing.JLabel();
        passwordUsuario = new javax.swing.JPasswordField();
        botonFacil = new javax.swing.JRadioButton();
        botonMedio = new javax.swing.JRadioButton();
        botonDificil = new javax.swing.JRadioButton();
        botonLogIn = new javax.swing.JButton();
        botonNuevoUsuario = new javax.swing.JButton();

        labelUsuario.setText("Usuario:");

        labelPasswd.setText("Contraseña:");

        nombreUsuario.setText("Usuario");
        nombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreUsuarioMouseClicked(evt);
            }
        });
        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });

        labelPideSelDif.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        labelPideSelDif.setText("Selecciona un nivel de dificultad");

        labelBienvenida.setFont(new java.awt.Font("Didact Gothic", 1, 18)); // NOI18N
        labelBienvenida.setText("Bienvenido al Buscaminas!!!");

        passwordUsuario.setText("jPasswordField1");
        passwordUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordUsuarioMouseClicked(evt);
            }
        });

        botonFacil.setText("Facil");

        botonMedio.setText("Medio");

        botonDificil.setText("Dificil");

        botonLogIn.setText("Login");
        botonLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLogInMouseClicked(evt);
            }
        });

        botonNuevoUsuario.setText("Nuevo Usuario");
        botonNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNuevoUsuarioMouseClicked(evt);
            }
        });
        botonNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelPideSelDif)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botonLogIn))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(labelPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addComponent(botonFacil))
                                                        .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(botonMedio)
                                                                .addGap(115, 115, 115)
                                                                .addComponent(botonDificil))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(passwordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                                                .addComponent(botonNuevoUsuario)))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(labelBienvenida)
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelUsuario)
                                        .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonLogIn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelPasswd)
                                        .addComponent(passwordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonNuevoUsuario))
                                .addGap(34, 34, 34)
                                .addComponent(labelPideSelDif)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botonFacil)
                                        .addComponent(botonMedio)
                                        .addComponent(botonDificil))
                                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>

    public String getDificultad_juego(){
        return this.dificultad_juego;
    }

    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void botonNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void nombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        nombreUsuario.setText("");
    }

    private void passwordUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        passwordUsuario.setText("");
        this.setVisible(false);
    }

    private void botonLogInMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Jugador auxUser = new Jugador(nombreUsuario.getText(), passwordUsuario.getPassword().toString());
        if (ListaJugadores.getMiListaJugadores().getJugador(auxUser.getNombreJugador()) != null) {
            if (ListaJugadores.getMiListaJugadores().getJugador(auxUser.getNombreJugador()).comprobarPasswd(auxUser.getContrasena())){

            }
                //por hacer!!!
        }
    }

    private void botonNuevoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {

    }


    private void inicializarBotonesDificultad() {
        //al inicializar la clase instancia los botones JRadioButton
        //dentro de un grupo de botones para que solo uno de ellos pueda
        //estar pulsado a la vez

        botonFacil.setActionCommand("facil");
        botonMedio.setActionCommand("medio");
        botonDificil.setActionCommand("dificil");

        grupoBotonesDif.add(botonFacil);
        grupoBotonesDif.add(botonMedio);
        grupoBotonesDif.add(botonDificil);

        //Regsitramos un listener para los radio buttons
        botonFacil.addActionListener(this);
        botonMedio.addActionListener(this);
        botonDificil.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        dificultad_juego = e.getActionCommand();
    }

    // Variables declaration - do not modify
    private javax.swing.JRadioButton botonDificil;
    private javax.swing.JRadioButton botonFacil;
    private javax.swing.JButton botonLogIn;
    private javax.swing.JRadioButton botonMedio;
    private javax.swing.JButton botonNuevoUsuario;
    private javax.swing.ButtonGroup grupoBotonesDif;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JLabel labelPasswd;
    private javax.swing.JLabel labelPideSelDif;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JPasswordField passwordUsuario;
    // End of variables declaration
}
