/*
 * The MIT License
 *
 * Copyright 2016 Josu Alvarez <jalvarez041.ehu.eus>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

import java.util.Arrays;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 * @author josu
 */
public class TableroPruebas extends JFrame implements ActionListener {

    String dificultad_juego = "facil";
    int x = 0, y = 0;
    int numCasillas, contMinas;


    /**
     * Creates new form TableroPruebas
     */
    public TableroPruebas() {
        initComponents();
        inicializarBotonesDificultad();
    }

    private void inicializarBotonesDificultad() {
        //al inicializar la clase instancia los botones JRadioButton
        //dentro de un grupo de botones para que solo uno de ellos pueda
        //estar pulsado a la vez

        boton_facil.setActionCommand("facil");
        boton_medio.setActionCommand("medio");
        boton_dificil.setActionCommand("dificil");

        grupoBotones.add(boton_facil);
        grupoBotones.add(boton_medio);
        grupoBotones.add(boton_dificil);

        //Regsitramos un listener para los radio buttons
        boton_facil.addActionListener(this);
        boton_medio.addActionListener(this);
        boton_dificil.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        dificultad_juego = e.getActionCommand();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new ButtonGroup();
        panel_info = new JPanel();
        label_peticionJugador = new JLabel();
        texto_nombreJugador = new JTextField();
        label_contraseña = new JLabel();
        texto_password = new JPasswordField();
        boton_LogIn = new JButton();
        boton_NewUser = new JButton();
        panel_juego = new JPanel();
        label_seleccionDificultad = new JLabel();
        label_difFacil = new JLabel();
        label_difMedia = new JLabel();
        label_difDificil = new JLabel();
        boton_facil = new JRadioButton();
        boton_medio = new JRadioButton();
        boton_dificil = new JRadioButton();
        barra_menu = new JMenuBar();
        menu_archivo = new JMenu();
        menuArhivo_nuevaPartida = new JMenuItem();
        menuArchivo_ranking = new JMenuItem();
        menuArchivo_salir = new JMenuItem();
        menu_ayuda = new JMenu();
        menuAyuda_problemasfrecuentes = new JMenuItem();
        menuAyuda_FAQ = new JMenuItem();
        menuAyuda_acercade = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        label_peticionJugador.setText("Nombre:");

        texto_nombreJugador.setText("Jugador");
        texto_nombreJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto_nombreJugadorMouseClicked(evt);
            }
        });

        label_contraseña.setText("Contraseña:");

        texto_password.setText("textopassword");
        texto_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto_passwordMouseClicked(evt);
            }
        });

        boton_LogIn.setText("Login");
        boton_LogIn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                boton_LogInActionPerformed(evt);
            }
        });

        boton_NewUser.setText("Nuevo Usuario");
        boton_NewUser.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                boton_NewUserActionPerformed(evt);
            }
        });

        GroupLayout panel_infoLayout = new GroupLayout(panel_info);
        panel_info.setLayout(panel_infoLayout);
        panel_infoLayout.setHorizontalGroup(
                panel_infoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(panel_infoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel_infoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(label_peticionJugador, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_contraseña))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_infoLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(texto_nombreJugador)
                                        .addComponent(texto_password))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(boton_LogIn, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(boton_NewUser)
                                .addGap(32, 32, 32))
        );
        panel_infoLayout.setVerticalGroup(
                panel_infoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(panel_infoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(panel_infoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(label_peticionJugador)
                                        .addComponent(texto_nombreJugador, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(panel_infoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(label_contraseña)
                                        .addComponent(texto_password, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                        .addGroup(panel_infoLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(panel_infoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(boton_LogIn)
                                        .addComponent(boton_NewUser))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_juego.setForeground(new Color(80, 80, 80));

        label_seleccionDificultad.setFont(new Font("DejaVu Sans", 0, 18)); // NOI18N
        label_seleccionDificultad.setText("Selecciona un nivel de dificultad:");

        label_difFacil.setText("(7 filas, 10 columnas / 10 minas)");

        label_difMedia.setText("(10 filas, 15 columnas / 30 minas)");

        label_difDificil.setText("(12 filas, 25 columnas / 75 minas)");

        boton_facil.setSelected(true);
        boton_facil.setText("Facil");

        boton_medio.setText("Medio");

        boton_dificil.setText("DIficil");

        GroupLayout panel_juegoLayout = new GroupLayout(panel_juego);
        panel_juego.setLayout(panel_juegoLayout);
        panel_juegoLayout.setHorizontalGroup(
                panel_juegoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, panel_juegoLayout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_juegoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(boton_dificil)
                                        .addComponent(boton_medio)
                                        .addComponent(boton_facil))
                                .addGap(39, 39, 39)
                                .addGroup(panel_juegoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(label_difFacil)
                                        .addGroup(panel_juegoLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                .addComponent(label_difMedia)
                                                .addComponent(label_difDificil)))
                                .addGap(107, 107, 107))
                        .addGroup(panel_juegoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label_seleccionDificultad, GroupLayout.PREFERRED_SIZE, 432, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_juegoLayout.setVerticalGroup(
                panel_juegoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(panel_juegoLayout.createSequentialGroup()
                                .addContainerGap(57, Short.MAX_VALUE)
                                .addComponent(label_seleccionDificultad, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(panel_juegoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(label_difFacil)
                                        .addComponent(boton_facil))
                                .addGap(18, 18, 18)
                                .addGroup(panel_juegoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(label_difMedia)
                                        .addComponent(boton_medio))
                                .addGap(18, 18, 18)
                                .addGroup(panel_juegoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(label_difDificil)
                                        .addComponent(boton_dificil))
                                .addGap(43, 43, 43))
        );

        menu_archivo.setText("Archivo");

        menuArhivo_nuevaPartida.setText("Nueva partida");
        menu_archivo.add(menuArhivo_nuevaPartida);

        menuArchivo_ranking.setText("Ranking de mejores jugadores");
        menu_archivo.add(menuArchivo_ranking);

        menuArchivo_salir.setText("Salir");
        menuArchivo_salir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuArchivo_salirActionPerformed(evt);
            }
        });
        menu_archivo.add(menuArchivo_salir);

        barra_menu.add(menu_archivo);

        menu_ayuda.setText("Ayuda");

        menuAyuda_problemasfrecuentes.setText("Problemas frecuentes ");
        menu_ayuda.add(menuAyuda_problemasfrecuentes);

        menuAyuda_FAQ.setText("F.A.Q");
        menu_ayuda.add(menuAyuda_FAQ);

        menuAyuda_acercade.setText("Acerca de");
        menu_ayuda.add(menuAyuda_acercade);

        barra_menu.add(menu_ayuda);

        setJMenuBar(barra_menu);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(panel_info, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_juego, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_info, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_juego, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArchivo_salirActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuArchivo_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0); //Cierra la ventana en caso de haber sido clickado
    }//GEN-LAST:event_menuArchivo_salirActionPerformed

    private void texto_nombreJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto_nombreJugadorMouseClicked
        // TODO add your handling code here:
        texto_nombreJugador.setText(""); // Cuando se clicka sobre el cuadro de texto se borra el texto
        //que haya previamente de forma automatica
    }//GEN-LAST:event_texto_nombreJugadorMouseClicked

    private void boton_LogInActionPerformed(ActionEvent evt) {//GEN-FIRST:event_boton_LogInActionPerformed
        Usuario auxUser = new Usuario(texto_nombreJugador.getText(), texto_password.getPassword());
        if (ListaUsuarios.getMiListaUsuarios().esta(auxUser)) {
            this.iniciarPartida(auxUser, dificultad_juego);
        } else {
            JOptionPane.showMessageDialog(rootPane, "El usuario no existe. Pruebe creando un nuevo usuario");
        }
    }//GEN-LAST:event_boton_LogInActionPerformed

    private void boton_NewUserActionPerformed(ActionEvent evt) {//GEN-FIRST:event_boton_NewUserActionPerformed
        // TODO add your handling code here:
        Usuario auxUser = new Usuario(texto_nombreJugador.getText(), texto_password.getPassword());
        if (ListaUsuarios.getMiListaUsuarios().esta(auxUser)) {
            JOptionPane.showMessageDialog(rootPane, "El usuario ya existe. Pruebe haciendo login");
        } else {
            ListaUsuarios.getMiListaUsuarios().anadirUsuario(auxUser);
            this.iniciarPartida(auxUser, dificultad_juego);
        }
    }//GEN-LAST:event_boton_NewUserActionPerformed

    private void texto_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto_passwordMouseClicked
        // TODO add your handling code here:
        texto_password.setText("");
    }//GEN-LAST:event_texto_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroPruebas().setVisible(true);
            }
        });
    }

    private void iniciarPartida(Usuario pUsuario, String pDif) {
        this.establecerMedidasTablero(pDif);
        this.generarTableroMinas();
        this.generarBarraInformacionJuego();
        this.paintAll(this.getGraphics()); //reinicia los graficos de todas los paneles del frame

    }

    private void establecerMedidasTablero(String pDif) {

        if (null != pDif) {
            switch (pDif) {
                case "facil":
                    x = 7;
                    y = 10;
                    break;
                case "medio":
                    x = 10;
                    y = 15;
                    break;
                case "dificil":
                    x = 12;
                    y = 25;
                    break;
                default:
                    break;
            }
        }
        numCasillas = x * y;
    }

    private void generarTableroMinas() {

        //this.getContentPane().remove(panel_info); //Borra el panel superior y asi queda maximizado el panel_juego

        this.panel_juego.removeAll(); //Eliminamos el contenido del panel
        this.panel_juego.setLayout(new GridLayout(x, y));

        contMinas = 0;

        for (int i = 0; i < x; i++) { //nos movemos a traves de las filas
            for (int j = 0; j < y; j++) { //nos movemos a traves de las columnas

                CasillaGrafica temp = new CasillaGrafica(); //creamos una casilla temporal
                temp.addActionListener(this); //de esta forma todos los botones que vayamos creando, al ser clikados
                // ejecutan el metodo ActionPerformed declarado arriba
                if (temp.estaMinado()) { //comprobamos si es una mina
                    contMinas++; //aumentamos el contador de minas
                }
                temp.setVisible(true); //hacemos que la casilla temporal que hemos creado sea visible
                this.panel_juego.add(temp); //añadimos la casilla al panel de juego (JPanel)
            }
        }
    }

    private void generarBarraInformacionJuego() {
        this.panel_info.removeAll(); //Eliminamos el contenido del panel
        this.panel_info.setLayout(new GridLayout(1, 1));


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenuBar barra_menu;
    private JButton boton_LogIn;
    private JButton boton_NewUser;
    private JRadioButton boton_dificil;
    private JRadioButton boton_facil;
    private JRadioButton boton_medio;
    private ButtonGroup grupoBotones;
    private JLabel label_contraseña;
    private JLabel label_difDificil;
    private JLabel label_difFacil;
    private JLabel label_difMedia;
    private JLabel label_peticionJugador;
    private JLabel label_seleccionDificultad;
    private JMenuItem menuArchivo_ranking;
    private JMenuItem menuArchivo_salir;
    private JMenuItem menuArhivo_nuevaPartida;
    private JMenuItem menuAyuda_FAQ;
    private JMenuItem menuAyuda_acercade;
    private JMenuItem menuAyuda_problemasfrecuentes;
    private JMenu menu_archivo;
    private JMenu menu_ayuda;
    private JPanel panel_info;
    private JPanel panel_juego;
    private JTextField texto_nombreJugador;
    private JPasswordField texto_password;
    // End of variables declaration//GEN-END:variables

}
