/*
 * Copyright [2016] [Josu]
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

import java.util.ArrayList;

/**
     *
     * @author Josu Alvarez <jalvarez041.ehu.eus>
     */
    public class VistaRanking extends javax.swing.JFrame {

    private static VistaRanking miVistaRanking;

        /**
         * Creates new form VistaRanking
         */
        private VistaRanking() {
            initComponents();

            Ranking.getMiRanking().crearListaRanking();
            ArrayList<InfoPartida> top10 = Ranking.getMiRanking().obtenerDiezMejores();

            for(int i=0; i<top10.size();i++){
                switch (i){
                    case 1:
                        jLabel4.setText(top10.get(i).getNombreJugador());
                        jLabel5.setText(String.valueOf(top10.get(i).getPuntuacion()));
                    case 2:
                        jLabel6.setText(top10.get(i).getNombreJugador());
                        jLabel7.setText(String.valueOf(top10.get(i).getPuntuacion()));
                    case 3:
                        jLabel8.setText(top10.get(i).getNombreJugador());
                        jLabel9.setText(String.valueOf(top10.get(i).getPuntuacion()));
                    case 4:
                        jLabel10.setText(top10.get(i).getNombreJugador());
                        jLabel11.setText(String.valueOf(top10.get(i).getPuntuacion()));
                    case 5:
                        jLabel12.setText(top10.get(i).getNombreJugador());
                        jLabel13.setText(String.valueOf(top10.get(i).getPuntuacion()));
                    case 6:
                        jLabel14.setText(top10.get(i).getNombreJugador());
                        jLabel15.setText(String.valueOf(top10.get(i).getPuntuacion()));
                    case 7:
                        jLabel16.setText(top10.get(i).getNombreJugador());
                        jLabel17.setText(String.valueOf(top10.get(i).getPuntuacion()));
                    case 8:
                        jLabel18.setText(top10.get(i).getNombreJugador());
                        jLabel19.setText(String.valueOf(top10.get(i).getPuntuacion()));
                    case 9:
                        jLabel20.setText(top10.get(i).getNombreJugador());
                        jLabel21.setText(String.valueOf(top10.get(i).getPuntuacion()));
                    case 10:
                        jLabel22.setText(top10.get(i).getNombreJugador());
                        jLabel23.setText(String.valueOf(top10.get(i).getPuntuacion()));
                }
            }
        }

    public static VistaRanking getMiVistaRanking(){
        if (miVistaRanking == null){
            miVistaRanking = new VistaRanking();
        }
        return miVistaRanking;
    }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            jLabel10 = new javax.swing.JLabel();
            jLabel11 = new javax.swing.JLabel();
            jLabel12 = new javax.swing.JLabel();
            jLabel13 = new javax.swing.JLabel();
            jLabel14 = new javax.swing.JLabel();
            jLabel15 = new javax.swing.JLabel();
            jLabel16 = new javax.swing.JLabel();
            jLabel17 = new javax.swing.JLabel();
            jLabel18 = new javax.swing.JLabel();
            jLabel19 = new javax.swing.JLabel();
            jLabel20 = new javax.swing.JLabel();
            jLabel21 = new javax.swing.JLabel();
            jLabel22 = new javax.swing.JLabel();
            jLabel23 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Duru Sans", 1, 18)); // NOI18N
            jLabel1.setText("Top 10");

            jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
            jLabel2.setText("Jugador");

            jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
            jLabel3.setText("Puntuacion");

            jLabel4.setText("Jug1");

            jLabel5.setText("Punt1");

            jLabel6.setText("Jug2");

            jLabel7.setText("Jug3");

            jLabel8.setText("Jug4");

            jLabel9.setText("Jug5");

            jLabel10.setText("Jug6");

            jLabel11.setText("Punt2");

            jLabel12.setText("Punt3");

            jLabel13.setText("Punt4");

            jLabel14.setText("Punt5");

            jLabel15.setText("Punt6");

            jLabel16.setText("Jug7");

            jLabel17.setText("Punt7");

            jLabel18.setText("Jug8");

            jLabel19.setText("Punt8");

            jLabel20.setText("Jug9");

            jLabel21.setText("Punt9");

            jLabel22.setText("Jug10");

            jLabel23.setText("Punt10");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jLabel2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGap(63, 63, 63)
                                                                    .addComponent(jLabel1))
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGap(20, 20, 20)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                            .addComponent(jLabel22))
                                                                    .addGap(68, 68, 68)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(jLabel5)
                                                                                    .addComponent(jLabel11)
                                                                                    .addComponent(jLabel12)
                                                                                    .addComponent(jLabel13)
                                                                                    .addComponent(jLabel14)
                                                                                    .addComponent(jLabel15)
                                                                                    .addComponent(jLabel17)
                                                                                    .addComponent(jLabel19)
                                                                                    .addComponent(jLabel21))
                                                                            .addComponent(jLabel23))))
                                                    .addGap(0, 34, Short.MAX_VALUE)))
                                    .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23))
                                    .addContainerGap(33, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>

        // Variables declaration - do not modify
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        // End of variables declaration
    }


